map_type: costmap

obstacle_range: 4.0 # 2.0,1
raytrace_range: 5.5 # 3.0,2

transform_tolerance: 0.4 # 0.0

footprint: [[0.4,0.2], [0.4,-0.2], [-0.4,-0.2], [-0.4, 0.2]]
#robot_radius: 0.3 # 0.0
inflation_radius: 0.5 # 0.0,0.5
cost_scaling_factor: 2.0 #5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
