controller_frequency: 10

DWAPlannerROS:
  max_vel_x: 1.0 #0.5
  min_vel_x: -0.1 #0.01, -0.8
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 1.0
  min_vel_trans: 0.1
  max_rot_vel: 2.0 #2.5
  min_rot_vel: 1.7

  acc_lim_theta: 2.0
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  
  yaw_goal_tolerance: 0.2 #0.15
  xy_goal_tolerance: 0.2 #0.05

  sim_time: 1.5

  vx_samples: 8.0 #12
  vy_samples: 0
  vth_samples: 8.0 #20, 12
  
  path_distance_bias: 40.0 # 32.0
  goal_distance_bias: 24.0
  occdist_scale: 15.0
  publish_cost_grid_pc: true
  publish_traj_pc: true
  meter_scoring: true
  

