local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 6.0
   height: 6.0
   #inflation_radius: 0.8
   #cost_scaling_factor: 0.5
   resolution: 0.05
   static_map: false
   rolling_window: true
   meter_scoring: true
   publish_cost_grid: true
